services:
  web:
    build: .
    ports:
      - "8080:8080"
    networks:
      - offering
    depends_on:
      - database
  database:
    image: mongo:latest
    restart: always
    volumes:
      - ./data:/data/db
    networks:
      - offering
    ports:
      - 27017
networks:
  offering:
    driver: bridge 

volumes:
  data: